---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: hub.docker.maverick-apps.com/smartlocate/api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: api-env
      imagePullSecrets:
        - name: maverick-apps-registry
      terminationGracePeriodSeconds: 180