---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busdrivers
  annotations:
    dapr.io/enabled: true
    dapr.io/config: tracing
    dapr.io/app-id: busdrivers
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: busdrivers
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: busdrivers
    spec:
      containers:
      - name: busdrivers
        image: hub.docker.maverick-apps.com/smartlocate/bus-drivers:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: busdrivers-env
        - secretRef:
            name: busdrivers-secrets
      imagePullSecrets:
        - name: maverick-apps-registry
      terminationGracePeriodSeconds: 180