---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busroutes
  annotations:
    dapr.io/enabled: true
    dapr.io/config: tracing
    dapr.io/app-id: busroutes
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: busroutes
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: busroutes
    spec:
      containers:
      - name: busroutes
        image: hub.docker.maverick-apps.com/smartlocate/bus-routes:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: busroutes-env
        - secretRef:
            name: busroutes-secrets
      imagePullSecrets:
        - name: maverick-apps-registry
      terminationGracePeriodSeconds: 180