---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  annotations:
    dapr.io/enabled: true
    dapr.io/config: tracing
    dapr.io/app-id: identity
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: identity
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
      - name: identity
        image: hub.docker.maverick-apps.com/smartlocate/identity:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: identity-env
        - secretRef:
            name: identity-secrets
      imagePullSecrets:
        - name: maverick-apps-registry
      terminationGracePeriodSeconds: 180