---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: students
  annotations:
    dapr.io/enabled: true
    dapr.io/config: tracing
    dapr.io/app-id: students
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: students
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: students
    spec:
      containers:
      - name: students
        image: hub.docker.maverick-apps.com/smartlocate/students:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: students-env
        - secretRef:
            name: students-secrets
      imagePullSecrets:
        - name: maverick-apps-registry
      terminationGracePeriodSeconds: 180