---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminusers
  annotations:
    dapr.io/enabled: true
    dapr.io/config: tracing
    dapr.io/app-id: adminusers
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: adminusers
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: adminusers
    spec:
      containers:
      - name: adminusers
        image: hub.docker.maverick-apps.com/smartlocate/admins:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443
        envFrom:
        - configMapRef:
            name: adminusers-env
        - secretRef:
            name: adminusers-secrets
      imagePullSecrets:
        - name: maverick-apps-registry
      terminationGracePeriodSeconds: 180